# Generated by Django 4.1.4 on 2022-12-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default='1996-05-29'),
            preserve_default=False,
        ),
    ]
